###
### GET Root
GET http://localhost:10080/ HTTP/1.1

###
### GET Hello
GET http://localhost:10080/hello HTTP/1.1

###
### GET Headers
GET http://localhost:10080/headers HTTP/1.1


###
### POST Something
POST http://localhost:10080/webhooks/github HTTP/1.1

{
    "name" : "Zomaareentje",
    "test" : "Endannogwat"
}


###
### GET Root
GET http://192.168.1.201:80/ HTTP/1.1

###
### POST Something
POST http://192.168.1.201:80/webhooks/github/http-logger HTTP/1.1

{
    "name" : "Zomaareentje",
    "test" : "Endannogwat"
}




###
### POST Something
POST http://demo.kleinloog.ch/webhooks/github/http-logger HTTP/1.1

{
    "name" : "Zomaareentje",
    "test" : "Endannogwat"
}