apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-logger.fullname" . }}
  labels:
    {{- include "http-logger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "http-logger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "http-logger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: http-checks
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            port: 8080
            path: /alive
          initialDelaySeconds: 0.5
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 8 }}
