apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-logger.fullname" . }}
  labels:
    {{- include "http-logger.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "http-logger.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
